from collections.abc import AsyncGenerator

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from .config import settings


class Base(DeclarativeBase):
    pass


engine = create_async_engine(settings.database_url, echo=False, pool_pre_ping=True)
SessionLocal = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


async def get_session() -> AsyncGenerator[AsyncSession, None]:
    async with SessionLocal() as session:
        yield session


async def init_db() -> None:
    # En produccion esto deberia vivir en migraciones, pero este demo usa create_all.
    from . import models  # noqa: F401  (registra los modelos en el metadata)
    from .models import AppProject, Conversation

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
        # Migración ligera para bases existentes: añade columnas nuevas si faltan.
        # create_all no altera tablas ya creadas, así que lo hacemos explícito.
        await conn.execute(
            text(
                "ALTER TABLE app_projects "
                "ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'draft'"
            )
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS slug VARCHAR(64)")
        )
        await conn.execute(
            text(
                "ALTER TABLE app_projects "
                "ADD COLUMN IF NOT EXISTS deploy_state VARCHAR(20) NOT NULL DEFAULT 'idle'"
            )
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS url VARCHAR(255)")
        )
        await conn.execute(
            text("ALTER TABLE mcp_connections ADD COLUMN IF NOT EXISTS env_json TEXT")
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS dashboard JSON")
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS app_spec JSON")
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS deploy_stage VARCHAR(80)")
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS shared_emails JSON")
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS owner_email VARCHAR(255)")
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS build_artifacts JSON")
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS pending_edits JSON")
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS icon VARCHAR(16)")
        )
        await conn.execute(
            text("ALTER TABLE app_projects ADD COLUMN IF NOT EXISTS color VARCHAR(16)")
        )
        # Si el backend reinició durante un deploy, la tarea murió: reseteamos los
        # despliegues huérfanos (no pueden seguir corriendo) para no dejarlos colgados.
        await conn.execute(
            text(
                "UPDATE app_projects SET deploy_state='idle', deploy_stage=NULL "
                "WHERE deploy_state='deploying'"
            )
        )
        # Orden monotónico de mensajes (created_at empata dentro de un mismo commit).
        await conn.execute(
            text(
                "ALTER TABLE messages ADD COLUMN IF NOT EXISTS seq BIGINT "
                "GENERATED BY DEFAULT AS IDENTITY"
            )
        )
        # Conexiones por usuario: user_sub + unicidad (app, user, provider).
        await conn.execute(
            text("ALTER TABLE connections ADD COLUMN IF NOT EXISTS user_sub VARCHAR(255)")
        )
        await conn.execute(
            text(
                "ALTER TABLE connections "
                "DROP CONSTRAINT IF EXISTS uq_connection_app_provider"
            )
        )
        await conn.execute(
            text(
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_conn_app_user_provider "
                "ON connections (app_id, user_sub, provider)"
            )
        )

    async with SessionLocal() as session:
        conversations = (await session.execute(select(Conversation))).scalars().all()
        existing_ids = set(
            (await session.execute(select(AppProject.conversation_id))).scalars().all()
        )
        for conversation in conversations:
            if conversation.id in existing_ids:
                continue
            session.add(
                AppProject(
                    conversation_id=conversation.id,
                    title=conversation.title or "Nueva app",
                )
            )
        await session.commit()
